# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a1640c4adc58b7a43c1a816c869a778d46604c92e64de3d9a1149a094a18f4494ebe2479f1a8657d239a077bf3a341b38ba0977ae343b157d1a0e236f413bde

test:
  secret_key_base: e8373846df9f39996f169d83ff0aa67a2bb34135fd38204e4d541029c6836e67fa600d6d4179cafd0d8083572a219dd8ea0e5b1379b0b4333ec8c4dd4db2d1aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
