# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss_relationship',
            old_name='boss_id',
            new_name='boss',
        ),
        migrations.RenameField(
            model_name='boss_relationship',
            old_name='underling_id',
            new_name='underling',
        ),
    ]
