# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170417_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RenameField(
            model_name='secret',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='main.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
